---
- hosts: all
  vars:
     contents: "{{ lookup('file', '/home/ravijaya/Documents/foo.txt') }}"

  tasks:

     - debug:
         msg: the value of foo.txt is {{ contents }} as seen today {{ lookup('pipe', 'date +"%Y-%m-%d"') }}
